apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krawl.fullname" . }}-wordlists
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
data:
  wordlists.json: |
    {{- .Values.wordlists | toJson | nindent 4 }}
