apiVersion: v2
name: krawl-chart
description: A Helm chart for Krawl honeypot server
type: application
version: 0.1.2
appVersion: "1.0.0"
keywords:
  - honeypot
  - security
  - krawl
maintainers:
  - name: blessedrebus
home: https://github.com/blessedrebus/krawl
sources:
  - https://github.com/blessedrebus/krawl
